package com.nf147.sss.entity;

public class SssAssociation1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_association_1.ord_orderID
     *
     * @mbg.generated
     */
    private String ordOrderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_association_1.del_deliveryReceiptID
     *
     * @mbg.generated
     */
    private String delDeliveryreceiptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_association_1.order_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_association_1.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    private String deliveryreceiptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_association_1.ord_orderID
     *
     * @return the value of sss_association_1.ord_orderID
     *
     * @mbg.generated
     */
    public String getOrdOrderid() {
        return ordOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_association_1.ord_orderID
     *
     * @param ordOrderid the value for sss_association_1.ord_orderID
     *
     * @mbg.generated
     */
    public void setOrdOrderid(String ordOrderid) {
        this.ordOrderid = ordOrderid == null ? null : ordOrderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_association_1.del_deliveryReceiptID
     *
     * @return the value of sss_association_1.del_deliveryReceiptID
     *
     * @mbg.generated
     */
    public String getDelDeliveryreceiptid() {
        return delDeliveryreceiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_association_1.del_deliveryReceiptID
     *
     * @param delDeliveryreceiptid the value for sss_association_1.del_deliveryReceiptID
     *
     * @mbg.generated
     */
    public void setDelDeliveryreceiptid(String delDeliveryreceiptid) {
        this.delDeliveryreceiptid = delDeliveryreceiptid == null ? null : delDeliveryreceiptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_association_1.order_ID
     *
     * @return the value of sss_association_1.order_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_association_1.order_ID
     *
     * @param orderId the value for sss_association_1.order_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_association_1.deliveryReceipt_ID
     *
     * @return the value of sss_association_1.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptId() {
        return deliveryreceiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_association_1.deliveryReceipt_ID
     *
     * @param deliveryreceiptId the value for sss_association_1.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptId(String deliveryreceiptId) {
        this.deliveryreceiptId = deliveryreceiptId == null ? null : deliveryreceiptId.trim();
    }
}