package com.nf147.sss.entity;

import java.util.Date;

public class SssCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_ID
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.route_ID
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_Type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_Origin
     *
     * @mbg.generated
     */
    private String carOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.carPro_Date
     *
     * @mbg.generated
     */
    private Date carproDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.carBuy_Date
     *
     * @mbg.generated
     */
    private Date carbuyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_Capacity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_State
     *
     * @mbg.generated
     */
    private Boolean carState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_ID
     *
     * @return the value of sss_car.car_ID
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_ID
     *
     * @param carId the value for sss_car.car_ID
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.route_ID
     *
     * @return the value of sss_car.route_ID
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.route_ID
     *
     * @param routeId the value for sss_car.route_ID
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_Type
     *
     * @return the value of sss_car.car_Type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_Type
     *
     * @param carType the value for sss_car.car_Type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_Origin
     *
     * @return the value of sss_car.car_Origin
     *
     * @mbg.generated
     */
    public String getCarOrigin() {
        return carOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_Origin
     *
     * @param carOrigin the value for sss_car.car_Origin
     *
     * @mbg.generated
     */
    public void setCarOrigin(String carOrigin) {
        this.carOrigin = carOrigin == null ? null : carOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.carPro_Date
     *
     * @return the value of sss_car.carPro_Date
     *
     * @mbg.generated
     */
    public Date getCarproDate() {
        return carproDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.carPro_Date
     *
     * @param carproDate the value for sss_car.carPro_Date
     *
     * @mbg.generated
     */
    public void setCarproDate(Date carproDate) {
        this.carproDate = carproDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.carBuy_Date
     *
     * @return the value of sss_car.carBuy_Date
     *
     * @mbg.generated
     */
    public Date getCarbuyDate() {
        return carbuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.carBuy_Date
     *
     * @param carbuyDate the value for sss_car.carBuy_Date
     *
     * @mbg.generated
     */
    public void setCarbuyDate(Date carbuyDate) {
        this.carbuyDate = carbuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_Capacity
     *
     * @return the value of sss_car.car_Capacity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_Capacity
     *
     * @param carCapacity the value for sss_car.car_Capacity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_State
     *
     * @return the value of sss_car.car_State
     *
     * @mbg.generated
     */
    public Boolean getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_State
     *
     * @param carState the value for sss_car.car_State
     *
     * @mbg.generated
     */
    public void setCarState(Boolean carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.comment
     *
     * @return the value of sss_car.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.comment
     *
     * @param comment the value for sss_car.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}