package com.nf147.sss.entity;

import java.math.BigDecimal;

public class SssDeliveryrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.range_ID
     *
     * @mbg.generated
     */
    private String rangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.de_PID
     *
     * @mbg.generated
     */
    private String dePid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.area_ID
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.range_Name
     *
     * @mbg.generated
     */
    private String rangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.delivery_Price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.range_ID
     *
     * @return the value of sss_deliveryrange.range_ID
     *
     * @mbg.generated
     */
    public String getRangeId() {
        return rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.range_ID
     *
     * @param rangeId the value for sss_deliveryrange.range_ID
     *
     * @mbg.generated
     */
    public void setRangeId(String rangeId) {
        this.rangeId = rangeId == null ? null : rangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.de_PID
     *
     * @return the value of sss_deliveryrange.de_PID
     *
     * @mbg.generated
     */
    public String getDePid() {
        return dePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.de_PID
     *
     * @param dePid the value for sss_deliveryrange.de_PID
     *
     * @mbg.generated
     */
    public void setDePid(String dePid) {
        this.dePid = dePid == null ? null : dePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.area_ID
     *
     * @return the value of sss_deliveryrange.area_ID
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.area_ID
     *
     * @param areaId the value for sss_deliveryrange.area_ID
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.range_Name
     *
     * @return the value of sss_deliveryrange.range_Name
     *
     * @mbg.generated
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.range_Name
     *
     * @param rangeName the value for sss_deliveryrange.range_Name
     *
     * @mbg.generated
     */
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName == null ? null : rangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.delivery_Price
     *
     * @return the value of sss_deliveryrange.delivery_Price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.delivery_Price
     *
     * @param deliveryPrice the value for sss_deliveryrange.delivery_Price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.comment
     *
     * @return the value of sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.comment
     *
     * @param comment the value for sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}