package com.nf147.sss.entity;

import java.util.Date;

public class SssDeliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    private String deliveryreceiptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.start_City
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.end_City
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.mid_City
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.make_Date
     *
     * @mbg.generated
     */
    private Date makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryreceipt.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.deliveryReceipt_ID
     *
     * @return the value of sss_deliveryreceipt.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptId() {
        return deliveryreceiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.deliveryReceipt_ID
     *
     * @param deliveryreceiptId the value for sss_deliveryreceipt.deliveryReceipt_ID
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptId(String deliveryreceiptId) {
        this.deliveryreceiptId = deliveryreceiptId == null ? null : deliveryreceiptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.start_City
     *
     * @return the value of sss_deliveryreceipt.start_City
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.start_City
     *
     * @param startCity the value for sss_deliveryreceipt.start_City
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.end_City
     *
     * @return the value of sss_deliveryreceipt.end_City
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.end_City
     *
     * @param endCity the value for sss_deliveryreceipt.end_City
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.mid_City
     *
     * @return the value of sss_deliveryreceipt.mid_City
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.mid_City
     *
     * @param midCity the value for sss_deliveryreceipt.mid_City
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.make_Date
     *
     * @return the value of sss_deliveryreceipt.make_Date
     *
     * @mbg.generated
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.make_Date
     *
     * @param makeDate the value for sss_deliveryreceipt.make_Date
     *
     * @mbg.generated
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.state
     *
     * @return the value of sss_deliveryreceipt.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.state
     *
     * @param state the value for sss_deliveryreceipt.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryreceipt.comment
     *
     * @return the value of sss_deliveryreceipt.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryreceipt.comment
     *
     * @param comment the value for sss_deliveryreceipt.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}