package com.nf147.sss.entity;

public class SssDeliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_PID
     *
     * @mbg.generated
     */
    private String dePid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.mg_ID
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_PName
     *
     * @mbg.generated
     */
    private String dePname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.provimce_Name
     *
     * @mbg.generated
     */
    private String provimceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.city_Name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.mg_Name
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_PTel
     *
     * @mbg.generated
     */
    private String dePtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_PAddr
     *
     * @mbg.generated
     */
    private String dePaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_PID
     *
     * @return the value of sss_deliveryplace.de_PID
     *
     * @mbg.generated
     */
    public String getDePid() {
        return dePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_PID
     *
     * @param dePid the value for sss_deliveryplace.de_PID
     *
     * @mbg.generated
     */
    public void setDePid(String dePid) {
        this.dePid = dePid == null ? null : dePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.mg_ID
     *
     * @return the value of sss_deliveryplace.mg_ID
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.mg_ID
     *
     * @param mgId the value for sss_deliveryplace.mg_ID
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_PName
     *
     * @return the value of sss_deliveryplace.de_PName
     *
     * @mbg.generated
     */
    public String getDePname() {
        return dePname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_PName
     *
     * @param dePname the value for sss_deliveryplace.de_PName
     *
     * @mbg.generated
     */
    public void setDePname(String dePname) {
        this.dePname = dePname == null ? null : dePname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.provimce_Name
     *
     * @return the value of sss_deliveryplace.provimce_Name
     *
     * @mbg.generated
     */
    public String getProvimceName() {
        return provimceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.provimce_Name
     *
     * @param provimceName the value for sss_deliveryplace.provimce_Name
     *
     * @mbg.generated
     */
    public void setProvimceName(String provimceName) {
        this.provimceName = provimceName == null ? null : provimceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.city_Name
     *
     * @return the value of sss_deliveryplace.city_Name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.city_Name
     *
     * @param cityName the value for sss_deliveryplace.city_Name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.mg_Name
     *
     * @return the value of sss_deliveryplace.mg_Name
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.mg_Name
     *
     * @param mgName the value for sss_deliveryplace.mg_Name
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_PTel
     *
     * @return the value of sss_deliveryplace.de_PTel
     *
     * @mbg.generated
     */
    public String getDePtel() {
        return dePtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_PTel
     *
     * @param dePtel the value for sss_deliveryplace.de_PTel
     *
     * @mbg.generated
     */
    public void setDePtel(String dePtel) {
        this.dePtel = dePtel == null ? null : dePtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_PAddr
     *
     * @return the value of sss_deliveryplace.de_PAddr
     *
     * @mbg.generated
     */
    public String getDePaddr() {
        return dePaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_PAddr
     *
     * @param dePaddr the value for sss_deliveryplace.de_PAddr
     *
     * @mbg.generated
     */
    public void setDePaddr(String dePaddr) {
        this.dePaddr = dePaddr == null ? null : dePaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.comment
     *
     * @return the value of sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.comment
     *
     * @param comment the value for sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}