package com.nf147.sss.entity;

import java.math.BigDecimal;

public class SssOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_Id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.car_Id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.cu_Id
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_PName
     *
     * @mbg.generated
     */
    private String postPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_PTel
     *
     * @mbg.generated
     */
    private String postPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_PAddr
     *
     * @mbg.generated
     */
    private String postPaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_PName
     *
     * @mbg.generated
     */
    private String getPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_PTel
     *
     * @mbg.generated
     */
    private String getPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_PAddr
     *
     * @mbg.generated
     */
    private String getPaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.goods_Name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.good_Weight
     *
     * @mbg.generated
     */
    private Integer goodWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_Type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_State
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.transport_Price
     *
     * @mbg.generated
     */
    private BigDecimal transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.delivery_Price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.total_Price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_Id
     *
     * @return the value of sss_order.order_Id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_Id
     *
     * @param orderId the value for sss_order.order_Id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.car_Id
     *
     * @return the value of sss_order.car_Id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.car_Id
     *
     * @param carId the value for sss_order.car_Id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.cu_Id
     *
     * @return the value of sss_order.cu_Id
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.cu_Id
     *
     * @param cuId the value for sss_order.cu_Id
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_PName
     *
     * @return the value of sss_order.post_PName
     *
     * @mbg.generated
     */
    public String getPostPname() {
        return postPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_PName
     *
     * @param postPname the value for sss_order.post_PName
     *
     * @mbg.generated
     */
    public void setPostPname(String postPname) {
        this.postPname = postPname == null ? null : postPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_PTel
     *
     * @return the value of sss_order.post_PTel
     *
     * @mbg.generated
     */
    public String getPostPtel() {
        return postPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_PTel
     *
     * @param postPtel the value for sss_order.post_PTel
     *
     * @mbg.generated
     */
    public void setPostPtel(String postPtel) {
        this.postPtel = postPtel == null ? null : postPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_PAddr
     *
     * @return the value of sss_order.post_PAddr
     *
     * @mbg.generated
     */
    public String getPostPaddr() {
        return postPaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_PAddr
     *
     * @param postPaddr the value for sss_order.post_PAddr
     *
     * @mbg.generated
     */
    public void setPostPaddr(String postPaddr) {
        this.postPaddr = postPaddr == null ? null : postPaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_PName
     *
     * @return the value of sss_order.get_PName
     *
     * @mbg.generated
     */
    public String getGetPname() {
        return getPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_PName
     *
     * @param getPname the value for sss_order.get_PName
     *
     * @mbg.generated
     */
    public void setGetPname(String getPname) {
        this.getPname = getPname == null ? null : getPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_PTel
     *
     * @return the value of sss_order.get_PTel
     *
     * @mbg.generated
     */
    public String getGetPtel() {
        return getPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_PTel
     *
     * @param getPtel the value for sss_order.get_PTel
     *
     * @mbg.generated
     */
    public void setGetPtel(String getPtel) {
        this.getPtel = getPtel == null ? null : getPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_PAddr
     *
     * @return the value of sss_order.get_PAddr
     *
     * @mbg.generated
     */
    public String getGetPaddr() {
        return getPaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_PAddr
     *
     * @param getPaddr the value for sss_order.get_PAddr
     *
     * @mbg.generated
     */
    public void setGetPaddr(String getPaddr) {
        this.getPaddr = getPaddr == null ? null : getPaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.goods_Name
     *
     * @return the value of sss_order.goods_Name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.goods_Name
     *
     * @param goodsName the value for sss_order.goods_Name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.good_Weight
     *
     * @return the value of sss_order.good_Weight
     *
     * @mbg.generated
     */
    public Integer getGoodWeight() {
        return goodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.good_Weight
     *
     * @param goodWeight the value for sss_order.good_Weight
     *
     * @mbg.generated
     */
    public void setGoodWeight(Integer goodWeight) {
        this.goodWeight = goodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_Type
     *
     * @return the value of sss_order.order_Type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_Type
     *
     * @param orderType the value for sss_order.order_Type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_State
     *
     * @return the value of sss_order.order_State
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_State
     *
     * @param orderState the value for sss_order.order_State
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.transport_Price
     *
     * @return the value of sss_order.transport_Price
     *
     * @mbg.generated
     */
    public BigDecimal getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.transport_Price
     *
     * @param transportPrice the value for sss_order.transport_Price
     *
     * @mbg.generated
     */
    public void setTransportPrice(BigDecimal transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.delivery_Price
     *
     * @return the value of sss_order.delivery_Price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.delivery_Price
     *
     * @param deliveryPrice the value for sss_order.delivery_Price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.total_Price
     *
     * @return the value of sss_order.total_Price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.total_Price
     *
     * @param totalPrice the value for sss_order.total_Price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.comment
     *
     * @return the value of sss_order.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.comment
     *
     * @param comment the value for sss_order.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}