package com.nf147.sss.dao;

import com.nf147.sss.entity.SssDeliveryreceipt;
import java.util.List;

public interface SssDeliveryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryreceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int insert(SssDeliveryreceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    SssDeliveryreceipt selectByPrimaryKey(String deliveryreceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    List<SssDeliveryreceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssDeliveryreceipt record);
}